server:
  port: 10001
spring:
  application:
    name: server-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    sentinel:
      transport:
        port: 7777
        dashboard: 127.0.0.1:8888
      web-context-unify: false
      eager: true  #程序启动时，流控规则是否立即注册到Sentinel  true表示立即注册到Sentinel

    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowCredentials: true
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          route-id-prefix: gateway-    #生成流控规则API名称的前缀

  sleuth:
    sampler:
      probability: 1.0   #Sleuth的采样百分比
    zipkin:
      base-url: http://127.0.0.1:9411
      discovery-client-enabled: false   #配置成false，使Nacos将其当成一个URL，不要按服务名处理。